site_name: strutil
site_description: Easy to use, header only C++ 20 std::string utility library.
site_url: https://tgalaj.github.io/strutil/

repo_name: tgalaj/strutil
repo_url: https://github.com/tgalaj/strutil

theme: 
  language: en
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette: 
  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

   # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - mkdoxy:
      projects:
        strutil:
          src-dirs: ../../  # Adjust to your source directory
          full-doc: True
          doxy-cfg:
            SHOW_FILES: NO
            SHOW_USED_FILES: NO
            FILE_PATTERNS: "*.cpp *.h"  # Adjust for your languages
            RECURSIVE: NO
            EXAMPLE_PATH: ""
            FULL_PATH_NAMES: NO
            STRIP_FROM_PATH: "../../"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: 'index.md'
  - API:
    - strutil:
      - 'strutil': 'strutil/namespacestrutil.md'

use_directory_urls: true # (optional) for better links without .html extension