name: Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Install Python 
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        apt-get update -y && apt-get install doxygen graphviz -y
        pip install sphinx sphinx_rtd_theme sphinx-sitemap breathe docutils
    - name: Sphinx Build
      run: |
        sphinx-build docs temp_build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        folder: docs/temp_build/html # The folder the action should deploy.