name: Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install graphviz libclang1-11 libclang-cpp11

    - name: install doxygen from SF binary archives
      env:
        DOXYGEN_VERSION: 1.9.4
      run: |
        mkdir doxygen-bin-arc && cd doxygen-bin-arc
        curl -L https://sourceforge.net/projects/doxygen/files/rel-$DOXYGEN_VERSION/doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz > doxygen.tar.gz
        gunzip doxygen.tar.gz
        tar xf doxygen.tar
        cd doxygen-$DOXYGEN_VERSION
        sudo make install

    - name: Build the Docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        folder: docs/temp_build/html # The folder the action should deploy.