name: Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Build the Docs
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y doxygen && pip install breathe"
        docs-folder: "docs/"
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        folder: docs/temp_build/html # The folder the action should deploy.